// Auto-generated by GpuPaperDoll Exporter
// Generated at: 2026-05-05 22:15:41
// Prefab: UnitRoot

using System.Collections.Generic;

public static class UnitRoot_Config
{
    // ===== Group Variants ===== 
    public enum bodyallVariant : int
    {
        Devil_1 = 0,
        Elf_1 = 1,
        Elf_2 = 2,
        Human_1 = 3,
        Human_2 = 4,
        Human_3 = 5,
        Human_4 = 6,
        Human_5 = 7,
        Orc_1 = 8,
        Orc_2 = 9,
        Orc_3 = 10,
        Orc_4 = 11,
        Skelton_1 = 12,
    }

    public enum clothVariant : int
    {
        Cloth_1 = 0,
        Cloth_2 = 1,
        Cloth_3 = 2,
        Cloth_4 = 3,
        Cloth_5 = 4,
        Cloth_6 = 5,
        Cloth_7 = 6,
        Cloth_8 = 7,
        Cloth_9 = 8,
        Cloth_10 = 9,
        Cloth_11 = 10,
        Cloth_12 = 11,
        F_SR_Cloth = 12,
    }

    public enum armorVariant : int
    {
        Armor_1 = 0,
        Armor_2 = 1,
        Armor_3 = 2,
        Armor_4 = 3,
        Armor_5 = 4,
        Armor_6 = 5,
        Armor_7 = 6,
        Armor_8 = 7,
    }

    public enum eye_openVariant : int
    {
        Eye = 0,
        Eye0 = 1,
        Eye1 = 2,
        Eye2 = 3,
        Eye3 = 4,
        Eye4 = 5,
        Eye5 = 6,
        Eye6 = 7,
        Eye7 = 8,
        Eye8 = 9,
        Eye9 = 10,
        Eye10 = 11,
        Eye11 = 12,
        Eye16 = 13,
    }

    public enum eye_closeVariant : int
    {
        Eye_Close = 0,
    }

    public enum pantVariant : int
    {
        F_SR_Pants = 0,
        Foot_1 = 1,
        Foot_2 = 2,
        Foot_3 = 3,
        Foot_4 = 4,
    }

    // ===== Independent Slot Sprite Indices ===== 
    public enum backbackSprite : int
    {
        Back_1 = 0,
        Back_2 = 1,
        Back_3 = 2,
        BowBack_1 = 3,
        Soon_Back1 = 4,
        New_Back_01 = 5,
        New_Back_02 = 6,
    }

    public enum hairSprite : int
    {
        Hair_1 = 0,
        Hair_2 = 1,
        Hair_3 = 2,
        Hair_4 = 3,
        Hair_5 = 4,
        Hair_6 = 5,
        Hair_7 = 6,
        Hair_8 = 7,
        Hair_9 = 8,
    }

    public enum faceHairSprite : int
    {
        FaceHair_1 = 0,
        FaceHair_2 = 1,
        FaceHair_3 = 2,
        FaceHair_4 = 3,
        FaceHair_5 = 4,
    }

    public enum helmet1Sprite : int
    {
        F_SR_Helmet = 0,
        Helmet_1 = 1,
        Helmet_2 = 2,
        Helmet_3 = 3,
        Helmet_4 = 4,
        Helmet_5 = 5,
        Helmet_6 = 6,
        Helmet_7 = 7,
        Helmet_8 = 8,
        Helmet_9 = 9,
    }

    public enum helmet2Sprite : int
    {
        F_SR_Helmet = 0,
        Helmet_1 = 1,
        Helmet_2 = 2,
        Helmet_3 = 3,
        Helmet_4 = 4,
        Helmet_5 = 5,
        Helmet_6 = 6,
        Helmet_7 = 7,
        Helmet_8 = 8,
        Helmet_9 = 9,
    }

    public enum lweaponSprite : int
    {
        Sword_1 = 0,
        Sword_2 = 1,
        Sword_3 = 2,
        Sword_4 = 3,
        Sword_5 = 4,
        Sword_6 = 5,
        Axe_1 = 6,
        Bow_1 = 7,
        Soon_Spear = 8,
        Spear_1 = 9,
        Ward_1 = 10,
        F_SR_Hammer = 11,
    }

    public enum lshieldSprite : int
    {
        Shield_1 = 0,
        New_Shield_01 = 1,
        New_Shield_02 = 2,
        New_Shield_03 = 3,
        New_Shield_04 = 4,
    }

    public enum rweaponSprite : int
    {
        New_Weapon_01 = 0,
        New_Weapon_06 = 1,
        New_Weapon_17 = 2,
        New_Weapon_18 = 3,
        New_Weapon_19 = 4,
        New_Weapon_20 = 5,
        New_Weapon_09 = 6,
        New_Weapon_13 = 7,
        New_Weapon_14 = 8,
        New_Weapon_16 = 9,
        New_weapon_02 = 10,
        New_Weapon_04 = 11,
        New_Weapon_08 = 12,
        New_Weapon_10 = 13,
        New_Weapon_12 = 14,
        New_Weapon_15 = 15,
        New_Weapon_03 = 16,
        New_Weapon_05 = 17,
        New_Weapon_11 = 18,
        New_Weapon_07 = 19,
    }

    public enum rshieldSprite : int
    {
        Shield_1 = 0,
        New_Shield_01 = 1,
        New_Shield_02 = 2,
        New_Shield_03 = 3,
        New_Shield_04 = 4,
    }

    public enum shadowSprite : int
    {
        Shadow = 0,
    }

    // ===== Runtime Config ===== 
    [System.Serializable]
    public class Config
    {
        public int bodyallVariantIndex = 0; // bodyallVariant
        public int clothVariantIndex = 0; // clothVariant
        public int armorVariantIndex = 0; // armorVariant
        public int eye_openVariantIndex = 0; // eye_openVariant
        public int eye_closeVariantIndex = 0; // eye_closeVariant
        public int pantVariantIndex = 0; // pantVariant
        public int backbackSpriteIndex = 0; // backbackSprite
        public int hairSpriteIndex = 0; // hairSprite
        public int faceHairSpriteIndex = 0; // faceHairSprite
        public int helmet1SpriteIndex = 0; // helmet1Sprite
        public int helmet2SpriteIndex = 0; // helmet2Sprite
        public int lweaponSpriteIndex = 0; // lweaponSprite
        public int lshieldSpriteIndex = 0; // lshieldSprite
        public int rweaponSpriteIndex = 0; // rweaponSprite
        public int rshieldSpriteIndex = 0; // rshieldSprite
        public int shadowSpriteIndex = 0; // shadowSprite
    }
}
