using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// 根据导出数据生成 C# 脚本，包含 Group 和 Slot 的枚举定义
/// </summary>
public static class GpuCodeGen
{
    /// <summary>
    /// 生成枚举脚本
    /// </summary>
    public static string GenerateEnumScript(GpuRoleExportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by GpuPaperDoll Exporter");
        sb.AppendLine($"// Generated at: {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"// Prefab: {data.prefabName}");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"public static class {GetValidIdentifier(data.prefabName)}_Config");
        sb.AppendLine("{");

        // Group 枚举
        if (data.groups.Count > 0)
        {
            sb.AppendLine("    // ===== Group Variants ===== ");
            foreach (var g in data.groups)
            {
                string groupEnumName = GetValidIdentifier(g.groupName) + "Variant";
                sb.AppendLine($"    public enum {groupEnumName} : int");
                sb.AppendLine("    {");
                for (int i = 0; i < g.variants.Count; i++)
                {
                    string varName = GetValidIdentifier(g.variants[i].variantName);
                    sb.AppendLine($"        {varName} = {i},");
                }
                if (g.variants.Count == 0)
                {
                    sb.AppendLine("        None = -1,");
                }
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        // 独立 Slot 枚举
        var independentSlots = data.slots.Where(s => s.aliasName != "---").ToList();
        if (independentSlots.Count > 0)
        {
            sb.AppendLine("    // ===== Independent Slot Sprite Indices ===== ");
            foreach (var slot in independentSlots)
            {
                string slotEnumName = GetValidIdentifier(slot.aliasName) + "Sprite";
                sb.AppendLine($"    public enum {slotEnumName} : int");
                sb.AppendLine("    {");
                for (int i = 0; i < slot.availableSpriteIds.Length; i++)
                {
                    string spriteName = GetValidIdentifier(GetSpriteNameById(data, slot.availableSpriteIds[i]));
                    sb.AppendLine($"        {spriteName} = {i},");
                }
                if (slot.availableSpriteIds.Length == 0)
                {
                    sb.AppendLine("        None = -1,");
                }
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        // 运行时配置结构
        sb.AppendLine("    // ===== Runtime Config ===== ");
        sb.AppendLine("    [System.Serializable]");
        sb.AppendLine("    public class Config");
        sb.AppendLine("    {");

        // Group 方案选择
        foreach (var g in data.groups)
        {
            string groupEnumName = GetValidIdentifier(g.groupName) + "Variant";
            string fieldName = GetValidIdentifier(g.groupName) + "VariantIndex";
            sb.AppendLine($"        public int {fieldName} = 0; // {groupEnumName}");
        }

        // 独立 Slot Sprite 选择
        foreach (var slot in independentSlots)
        {
            string slotEnumName = GetValidIdentifier(slot.aliasName) + "Sprite";
            string fieldName = GetValidIdentifier(slot.aliasName) + "SpriteIndex";
            sb.AppendLine($"        public int {fieldName} = 0; // {slotEnumName}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetValidIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "None";

        // 替换非法字符
        var sb = new StringBuilder();
        bool first = true;
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
            {
                if (first && char.IsDigit(c))
                    sb.Append('_');
                sb.Append(c);
            }
            else
            {
                sb.Append('_');
            }
            first = false;
        }

        string result = sb.ToString();
        if (string.IsNullOrEmpty(result) || char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }

    private static string GetSpriteNameById(GpuRoleExportData data, int spriteId)
    {
        var entry = data.spriteUVs.FirstOrDefault(s => s.spriteId == spriteId);
        return entry != null ? entry.spriteName : "Unknown";
    }
}
